environment:
  SDL2_VERSION: 2.0.9
  MINGW_SHELL: C:\MinGW\msys\1.0\bin\bash
  CYG_ARCH: x86_64
  CYG_ROOT: C:/cygwin64

  matrix:
    - MACEMU_PROJECT: BasiliskII
      MACEMU_OS: Unix
    - MACEMU_PROJECT: SheepShaver
      MACEMU_OS: Windows


build: off

install:
  - set PATH=C:\cygwin64\bin;%PATH%
  - '%CYG_ROOT%\setup-%CYG_ARCH%.exe -qnNdO -R %CYG_ROOT%
    -l %CYG_ROOT%/var/cache/setup
    -P autoconf
    -P automake
    -P bison
    -P curl
    -P gcc-core
    -P gcc-g++
    -P gettext
    -P gettext-devel
    -P git
    -P intltool
    -P libgmp-devel
    -P libiconv
    -P libncurses-devel
    -P libreadline-devel
    -P libtool
    -P make
    -P mingw-binutils
    -P mingw-gcc-core
    -P mingw-gcc-g++
    -P mingw-pthreads
    -P mingw-runtime
    -P mingw-w32api
    -P pkg-config
    -P wget'
  - IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\SDL2-%SDL2_VERSION%.zip appveyor DownloadFile http://libsdl.org/release/SDL2-%SDL2_VERSION%.zip
  - unzip -o SDL2-%SDL2_VERSION%.zip
  - ren SDL2-%SDL2_VERSION% my_SDL2
  - '%MINGW_SHELL% -c "export PATH=.:/usr/local/bin:/mingw/bin:/bin:$PATH && cd my_SDL2 && ./autogen.sh && ./configure --disable-shared && make && make install"'


test_script:
  - ps: $ProgressPreference = "SilentlyContinue"
  - 'echo %MACEMU_PROJECT%'
  - 'cd %MACEMU_PROJECT%'
  - ps: ($env:MACEMU_PROJECT -eq "SheepShaver") -and $(make links)
  - 'cd src/%MACEMU_OS%'
  - '%MINGW_SHELL%  -c "export PATH=.:/usr/local/bin:/mingw/bin:/bin:$PATH && NO_CONFIGURE=1 ./autogen.sh && ./configure && make"'


# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
