language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: BADGE=linux
      script:
        - sudo apt install -y libsdl1.2-dev libgtk2.0-dev
        - cd src/Unix
        - NO_CONFIGURE=1 ./autogen.sh
        - ./configure --enable-sdl-video --enable-sdl-audio --disable-vosf --disable-jit-compiler --with-x --with-gtk --with-mon
        - make -j 4
    - os: osx
      env: BADGE=osx
      script:
        - true
